### ISSUE TITLE
Some RICO items are not found in the RICO or RICO/grwable categories

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#108]
Some RICO items are not found in the RICO or RICO/grwable categories, for example:

https://steamcommunity.com/sharedfiles/filedetails/?id=1275003434

Searching without category:
![image](https://user-images.githubusercontent.com/30873812/99941263-06488300-2d6e-11eb-9253-e4fa9c19d096.png)

With RICO enabled:
![image](https://user-images.githubusercontent.com/30873812/99941316-1bbdad00-2d6e-11eb-92ca-9a1b85462fdf.png)

With RICO/growable enabled:
![image](https://user-images.githubusercontent.com/30873812/99941351-2a0bc900-2d6e-11eb-9097-69009c6af320.png)

While the RICO settings seem fine:
![image](https://user-images.githubusercontent.com/30873812/99941384-3bed6c00-2d6e-11eb-8b94-710e57994f2c.png)

**Comment by sway2020** [comment]
@Sipke82 What asset type does it say in Find It's thumbnail pop-up?

**Comment by sway2020** [comment]
@Sipke82 I noticed that in the screenshots you set the building size filter to be Allx4, but RICO mod says the building is 11x7. I guess this is the reason?

**Comment by Sipke82** [comment]
Ah yes, silly me, Thank you
