### ISSUE TITLE
Option to ignore Alt+1..9 unless Find It open?

### ISSUE THREAD

**Issue by originalfoo** [sway2020/FindIt2#135]
TM:PE speed limits tool is getting a big makeover, and one of the enhancements (when speed tool window is visible) is to use `Alt`+`0..9` to select speed (eg. Alt+2 = 20 km/h). However, this causes Find It to open, even though the TM:PE tool is active.

Would it be possible to add option to Find It which, when enabled, ignores `Alt`+`0..9` if Find It toolbar is not visible?

TM:PE is getting an option to disable it's `Alt`+`0..9` shortcuts so that users can let Find It own those shortcuts if desired.

**Comment by sway2020** [comment]
Yes I'll add an option to ignore most keyboard shortcuts when Find It's panel is not visible. I am also considering changing the default shortcuts. Do you know if any mod is using Ctrl + 0-9?

**Comment by originalfoo** [comment]
[Broken Nodes Detector](https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984) mod by @krzychu124 uses `Ctrl`+`0` (zero) to open its UI

**Comment by krzychu124** [comment]
> [Broken Nodes Detector](https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984) mod by @krzychu124 uses `Ctrl`+`0` (zero) to open its UI

Yeah, that's default one, but you can change is in the options 😉

**Comment by sway2020** [comment]
This change is included in the newest workshop Find It 2 beta. I will update the main version in a few days

**Comment by kianzarrin** [comment]
@sway2020 I just saw this. we can resolve such conflicts through UUI hotkey conflict resolutions. but it seems that you managed to find an alternate solution.

**Comment by sway2020** [comment]
@kianzarrin I'll check out UUI's documentation. Modtools and Find It both are using Ctrl + F and this one hasn't been solved yet
