### ISSUE TITLE
2.8.0 causes crash on loading save (when using Linux)

### ISSUE THREAD

**Issue by samtoxie** [sway2020/FindIt2#159]
### 2.8.0 causes game crash when loading a savegame (on linux)
Since the new 2.8.0 update I'm experiencing issues launching a savegame on linux. Haven't tried windows as I don't use it. I've included the player.log from both with 2.8.0 and with 2.7.9, but I'm not able myself to find anything about it in the logfiles.

I'll try and see if I can find what causes it by looking at the changes between the versions.

### Environment
OS: Arch Linux (Kernel 5.16.10-arch1-1)
Runtime: Steam-Native (prefer system binaries over bundled libs), however issue also appears when using steams bundled libs
Plugins used: https://gist.github.com/samtoxie/f712628650158801720a397e83ef122e

### Logs
2.8.0: https://gist.github.com/samtoxie/1c650c8b170060323215f884219b578b
2.7.9: https://gist.github.com/samtoxie/c55a40a9cafaf08697f62f534c148c1f

Not sure if there is also a separate mod specific logfile, if so let me know and I'll include those

**Comment by sway2020** [comment]
I actually tested it on Linux before I released the update (Pop OS, Flatpak Steam, kernel 5.15.23) and it worked fine. I'll try it in a VM with arch-based distro when I have time. The only significant difference between 2.8.0 and 2.7.9 is I updated the bundled Harmony 2 API .dll file. I don't see any error message from Find It in the log either. Can you try a new game with only Find It enabled?

**Comment by sway2020** [comment]
btw Network Multitool and Transport Lines Manager mods are both throwing errors in the log. Not sure if this is related

**Comment by samtoxie** [comment]
Yeah I'm actually getting it every so often with the older version too now, starting to think it might me more related to something else. I'll do some deeper digging.

**Comment by samtoxie** [comment]
Hmm yeah I'm starting to suspect this isn't caused by Find It itself after some debugging, but just unluckily seemed like the culprit due to the recent update and magically my game working without it or with the older version whenever I tried that.

I think it's more likely to be an issue indeed with either TLM or network multitool, which for some reason got supressed when changing Find It versions or not using it. To add I've also started to encounter this when actually using to older version during debugging (whether downloaded or compiled myself from the same commit), albeit less often than I've had with 2.8.0. But that might have just been luck or something

**Comment by samtoxie** [comment]
After some more digging, it definitely seems like a problem in TLM. I'll close this issue as I don't suspect Find It has an actual play in this, besides exposing me to it for the first time. I was already considering TLM as the culprit, but the fact it seemed to work with an older FindIt started to make me doubt.

Cheers anyways!
