### ISSUE TITLE
Enhancement: More RICO building size filter options

### ISSUE THREAD

**Issue by peanutsrevenge** [sway2020/FindIt2#20]
It's been possible to filter RICO/Growables by size, however a great number of buildings are over the 4x4 limit now (especially for BIG builders like myself). Could that be expanded, perhaps a 5-8, 9-12, 13+ or something tacked on.

Some of this irritation would probably be resolved with the addition of the requested "sort" feature, but more is better, right ;)

Many Thanks regardless.
Peanut

**Comment by sway2020** [comment]
The code on size filter left by SamsamTS is pretty expandable so I'll check it up. I think this may actually be better than sorting by size.

**Comment by sway2020** [comment]
WIP. Will add 5-8, 9-12, 13+ to rico.

**Comment by sway2020** [comment]
Implemented in da1e97acd51831cbe8c891a27023aca58ce5036d. Probably will be included in the upcoming v1.6.5 release.

**Comment by peanutsrevenge** [comment]
Cheers dude.
Now if I only I can figure out what's causing my crashes so I can actually play the damn game and enjoy the increased play-ability you've brought xD

**Comment by sway2020** [comment]
@PeanutsRevenge is that the same key not found error some people are having? Would you mind sharing the output log or error message?

**Comment by peanutsrevenge** [comment]
@sway2020 There's nothing in the log, whole system simply black screen's/locks up. It's probably a mod conflict, I'm just sick of hunting for conflicting mods.
The game'll run (as I found out yesterday) indefinitely... so long as I don't "do" anything, then it died as usual a few minutes later. 
So modded, much frustration.
N.B The last output.log was too big (2MB) for sites, I'll try and irritate it quicker in a bit, I'd appreciate the extra, better informed eyes

**Comment by peanutsrevenge** [comment]
@sway2020 A few logs, this was new city, save, exit clean log. There's nothing further added on crash (including windows logs). I have a few suspects, but I've done this dance soo many times :'(

[Zipped logs on Firefox Send:](https://send.firefox.com/download/a6dd20488310a8d2/#hNSeNgwamzjx6qBVhbNjvw)
