### ISSUE TITLE
Bug: the mod makes the game display in English

### ISSUE THREAD

**Issue by sway2020** [sway2020/FindIt2#34]
From user report:" The language of the game after a reboot began to change to English, despite the fact that the selected language remains in the Settings. Disabling the mod fixes."

**Comment by algernon-A** [comment]
Cause identified as race condition with game LocaleManger initialisation.  Fix incoming shortly.

**Comment by algernon-A** [comment]
Fix uploaded as 77636cf4299a7fdd96ab2dc75c6cefb7719619a7

**Comment by sway2020** [comment]
@algernon-A thanks a lot!

**Comment by sway2020** [comment]
@algernon-A I did some testing and the mod always displays in English after I restart the game unless I change the game language again. I'll try to figure out the problem.

**Comment by sway2020** [comment]
I've located the problem. In **public void SetLanguage(int index)**,  (LocaleManager.exists) is always false when the game restarts so the fallback language is used. Don't know how to fix it yet.

**Comment by sway2020** [comment]
Fixed in 7ebc7bf0d4185703c5c5e5ff2d4bf375f2a07c8b. @algernon-A  I'm not sure if this is a good way to do it.
