### ISSUE TITLE
Request: Network categories

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#43]
It would be nice to have different category's for networks, for example:
- small/medium/large roads
- highways
- Paths
- tracks
- decorative
- quays
- ....
- ....

**Comment by sway2020** [comment]
I think the original game UI already works pretty well so this is not really necessary for Find It. This might be considered but probably very low priority. I'll see if other users make the same suggestions.

**Comment by sway2020** [comment]
Originally I thought this would be redundant, but now I think it would be useful if new network filter tabs can be used together with other filters. I'll try to add them.

**Comment by sway2020** [comment]
Changed my mind again.... The categorization of network assets are too messy, and I don't really want to touch them anymore.

**Comment by Sipke82** [comment]
It was ment to only differentiate between: Roads, Tracks, Paths and Other.
(perhaps quays)
Just like the move it categories.
But yes it is quite messy =)

Op di 4 aug. 2020 om 08:53 schreef sway2020 <notifications@github.com>:

**Comment by sway2020** [comment]
I got the road types working, but the game counts some other network assets as multiple types and I thought it was too much work to clear everything out. For example some walls are counted as path, fence, and water structure at the same time, it's a bit silly and I just stopped. I might come back to work on it tho.

**Comment by sway2020** [comment]
I think I'll just make filter tabs for some network types(roads, train tracks, pedestrian path) and leave other types in an unsorted tab.

**Comment by sway2020** [comment]
Added some in the new beta release (v2.0.1). I'll probably add more later.

**Comment by sway2020** [comment]
'Tiny Roads', 'Utility' and 'Train' added in v2.0.1-beta2. The rest will be kept in 'Unsorted' at the moment.
