### ISSUE TITLE
Request: Tree sizes filter

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#44]
Would be nice to have the same trees size (small/medium/large) filter available:
![image](https://user-images.githubusercontent.com/30873812/86274862-a2f96100-bbd2-11ea-9c92-8a3e2a978433.png)

**Comment by sway2020** [comment]
Same reason as #43 . I think the original game UI already works pretty well so this is not really necessary for Find It. This might be considered but probably very low priority. I'll see if other users make the same suggestions.

**Comment by sway2020** [comment]
This is how the game defines small, medium, and large trees.

size =  treeInfo.m_generatedInfo.m_size.y * (treeInfo.m_minScale + treeInfo.m_maxScale)  
size <= 16 is small tree  

size > 16f && size <= 30f is medium tree  

size > 30f is large tree

**Comment by sway2020** [comment]
Added in f77e915259a8403f7f9cb852600945fd1acfedcf
