### ISSUE TITLE
Request: Ability to perform combined growable and RICO search

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#45]
Would be nice to search for growables or RICO buildings in one go but be able to use all the fancy filters:
![image](https://user-images.githubusercontent.com/30873812/86275133-18653180-bbd3-11ea-8eb5-2af7cebe0b36.png)

**Comment by sway2020** [comment]
I was thinking about the same feature. Will be considered.

**Comment by Sipke82** [comment]
Perhaps it would be nice if the first "drop-up"menu is actualy a checkbox interface. 
![image](https://user-images.githubusercontent.com/30873812/86283487-7436b700-bbe1-11ea-8795-d0be8d861e0b.png)

**Comment by sway2020** [comment]
That can be difficult because the game doesn't have similar built-in UI components afaik. I could be wrong tho. If you see another mod has that UI function, let me know and I'll try to replicate.

**Comment by Sipke82** [comment]
Move It? 
it has checkbox based filters.

**Comment by sway2020** [comment]
I just noticed another problem. Prop, ploppable, growable/rico,(and potentially network and trees) have their own filter tabs so they can't get mixed easily by using checkboxes without a UI design overhaul. Growable and RICO use the same filter tabs so it would be easier to add a new drop-down menu entry for a growable/Rico mix.

**Comment by algernon-A** [comment]
Further confused by the fact that there is now such a thing as a 'RICO Growable' as well.  A checkbox could be implemented as a custom control, but since it really only makes sense for the RICO/Growable combination, probably not worth it.  Adding a third category that combines the two seems like it makes the most sense.

**Comment by sway2020** [comment]
Implemented. Need more testing.

**Comment by sway2020** [comment]
Included in v1.6.7 release. @Sipke82 I think this feature is pretty useful. Thanks for the suggestion!
