### ISSUE TITLE
Request: Differentiate between trees and props in the "all" search window

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#49]
Due to the "Tree and Vehicles Props" mod https://steamcommunity.com/sharedfiles/filedetails/?id=2033714682

we now have the possibility to have trees as actual trees or as props. It would be handy to see at a glance if the selection is a tree or a prop: ( of course i could select prop or tree pre filter, but we all know that we are as efficient (/lazy) as possible). Perhaps the thumbnail could have some kind of icon on top of it. Or a tooltip?

![image](https://user-images.githubusercontent.com/30873812/86487973-de756600-bd5f-11ea-8da4-f42fbe5a353d.png)

**Comment by algernon-A** [comment]
Will look at this as part of the overhauled thumbnail rendering.

**Comment by sway2020** [comment]
Not right on the thumbnail but now the thumbnail pop-up will show the asset type and sub-type.
![Screenshot](https://user-images.githubusercontent.com/65274619/89362696-644c4000-d683-11ea-9fcb-e8340e11f42d.png)

It's only included in the beta release at the moment.
https://steamcommunity.com/sharedfiles/filedetails/?id=2187834843
