### ISSUE TITLE
Enhancement: Make right clicking the "workshop icon"on a thumbnail to open the workshop page more user friendly

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#51]
Request: Clicking the "workshop icon"on a thumbnail to open the workshop page. Perhaps only with Shift click or something.

**Comment by sway2020** [comment]
It's already an existing feature in the original find it, you can open the workshop page by right clicking the icon. Or should we change it to left clicking?

**Comment by Sipke82** [comment]
Owh wow, Thanks! I didn't know that!

Op do 9 jul. 2020 om 21:38 schreef sway2020 <notifications@github.com>:

**Comment by sway2020** [comment]
Yup it's not very obvious. I'll probably add a tooltip message to the icon or change it to left clicking.

**Comment by Sipke82** [comment]
I think only a tool tip could be handy, or even a description of it at the workshop page would be sufficient. rightclick is fine imo
