### ISSUE TITLE
Request: Add sorting options

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#6]
could you add sorting options:
Date added
cost
size
etc

**Comment by sway2020** [comment]
Afaik right now the game doesn't track when an asset was added. It's probably still doable but will take some extra work and performance cost. The other sorting options will be easier to implement. Will be considered.

**Comment by sway2020** [comment]
I think one possible way to do it is to read the creation date of the workshop files when the game is loading, then match the files with the assets then rank them. It will increase loading time tho. I'll see if I can improve the loading time first before I start working on this sort by date feature.

**Comment by sway2020** [comment]
I just checked and it turns out the order of creation date doesn't equal to order of subscription date... dead end then

**Comment by sway2020** [comment]
I think I've done enough investigation on this thing. It's impossible to do a "sort by subscription date" since there's no easy way to know when an asset was subscribed. However it is still possible to implement a "sort by download" date and I'll start implement it.

**Comment by sway2020** [comment]
"sort by time downloaded" implemented in 9970925f130e4726e76c5114b002b5510d40c771. @Sipke82 if you have time can you help me test the feature? Thank you.  https://github.com/sway2020/CS-FindIt/tree/master/testing

**Comment by sway2020** [comment]
3 new RICO building size filter options were added in v1.6.5. I think it would work better than sort by building size. I am going to close this issue for now but it is still open for discussion.
