### ISSUE TITLE
Random selection from search results

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#65]
It would be nice to have a button that enable "random build mode"

For instance you have a certain search result, or by selecting a certain custom tag. Then you want to fill an area the results. I find myself often clicking a random building from the results, build 1, and select the next  and so on.. 

So it would be cool to have some kind of random selction mode, after 1 item is plopped. a next (random) item is selected to be plopped. etc.

![image](https://user-images.githubusercontent.com/30873812/88453446-2bcc8b00-ce67-11ea-8713-ed0ab4d566ff.png)

**Comment by sway2020** [comment]
Not 100% the same behavior as requested but a random selection button is added in eb2e51c6f505792a5978b6e4438197e30a4f4071.

**Comment by Sipke82** [comment]
I think it would be even cooler if this button could act as a toggle, when enabled:
it randomly selects a building. When you place the building it would automatically and randomly select the next building.

In the current form, you will have to click the button again.

**Comment by sway2020** [comment]
I did think about that idea but I don't think it can be done easily (or just I don't know how to code it)

**Comment by Sipke82** [comment]
Perhaps its worthwhile to check the forest brush code. It has that
functionality for trees.

Single Tree mode
In v1.2.8 I added Single Tree mode
Here I will explain how it works.

Using Single Tree mode

To use single tree mode, reduce brush size to 1.

While in single tree mode, you will see a rendered preview of the tree that
will get plopped next out of all the trees in your brush. This mode allows
precision placement of trees including ignoring collision by activating...

Op zo 2 aug. 2020 om 09:49 schreef sway2020 <notifications@github.com>:

**Comment by sway2020** [comment]
I'll look into it.

**Comment by sway2020** [comment]
With some tips from algernon I think I kinda have an idea how to do it. I'll work on this next week.

**Comment by gregorsimpson** [comment]
Just popping in here to suggest that this button be there in all the different categories, not just buildings. It would be equally useful to be able to select random props, trees and so on from the current results list.
Cheers!

**Comment by sway2020** [comment]
I'll add the random selection button to trees and props. I don't think it makes sense for ploppable and decals... But I can add it if you really want.

**Comment by sway2020** [comment]
Added random selection button to trees and props. 

It's only included in the beta release at the moment.
https://steamcommunity.com/sharedfiles/filedetails/?id=2187834843

@gregorsimpson your pull request was accepted and added to the beta release already. I moved the code block from FindIt.cs to UISearchBox.cs. Thank you for the contribution!

**Comment by gregorsimpson** [comment]
@sway2020 Thanks! If you don't mind, I really do think that having the random button available everywhere would make perfect sense. For example, I often find myself decorating a backyard using a number of "dirt" decals. As for ploppables, there are a number of corner buildings around that are filed under ploppables, or maybe I might want to just add a random park of, say, 3x3 size to a free lot. In both cases, having that button would be awesome :)

**Comment by sway2020** [comment]
No problem. I'll add those in next updates.

**Comment by gregorsimpson** [comment]
Cheers! It's much appreciated. I have a couple other small addons lying around somewhere, too. If I get the time to do it, expect further pull requests :)

**Comment by sway2020** [comment]
It kinda works but it is glitchy. It would correctly select a random building but the blue-ish preview overlay mesh attached to the cursor doesn't match the building that is going to be plopped. Need to find a better method for my harmony patch. Still WIP.

**Comment by sway2020** [comment]
@Sipke82 I added a random selection keyboard shortcut(default to Alt-V) in the latest beta update, and I think it works better than a "random build mode"(...and I haven't fixed the issues mentioned in my last comment). I'm going to close the issue for now but feel free to let me know if you have any other suggestion.

**Comment by Sipke82** [comment]
Thanks @sway2020 ! at least we dont need to move the mouse anymore then! Looking forward to test it.

However, I still believe that it would be even more convenient if it would automatically select the next random asset after placing one.

**Comment by sway2020** [comment]
@Sipke82 I'll come back to work on this later. It already somewhat works but I haven't overcome an issue: the mouse cursor preview doesn't match the actual building that is going to be placed.
