### ISSUE TITLE
Possible UI Cleanup?

### ISSUE THREAD

**Issue by Cgameworld** [sway2020/FindIt2#68]
The updates to this mod are awesome, though the UI feels a bit messy

Here's an idea I had to clean it up:
-Move all options to the top toolbar 
-hide middle bar when no subfilters visible

Without subfilters:
![toolbar-mockup1](https://user-images.githubusercontent.com/49973689/88496535-48091e80-cf72-11ea-8b53-7432dbad4bf9.png)

With subfilters:
![toolbar-mockup2](https://user-images.githubusercontent.com/49973689/88496534-47708800-cf72-11ea-99f3-50e0bbbfedc0.png)

Thoughts?

**Comment by sway2020** [comment]
I want to change the UI a bit too but I don't have any clear plan yet. I think there are some issues with this mockup:

- the top toolbox panel should stay at the same height or it would jump up/down when users switch between different asset types. Some users use mouse wheel to switch between asset types quickly without opening the drop-down.

- not enough space to put the building filters (level and size)

- just personal preference but I think checkbox/button are more intuitive than drop-down list.

**Comment by sway2020** [comment]
I do like the idea of having the custom tag icon instead of using the whole 'Show custom tag panel' thing. I'll adopt it if I can clear out enough space to put it in the top panel. Maybe make the search input box shorter?

Sorry I didn't take new screenshots. I just want to show that the top toolbox panel is pretty full now so I'll need to find a space to squeeze the custom tag icon in.

![2133885971_preview_PreviewImage7](https://user-images.githubusercontent.com/65274619/88500810-96bcb580-cf7e-11ea-844e-7ac6e3478a2a.png)

**Comment by algernon-A** [comment]
I think it might be time to extend the toolbar vertically for an extra row, and accomodating everything with in that.  I agree with keeping the size and layout static, even if some parts are simply blank some of the time.

**Comment by sway2020** [comment]
#64 #65 are related and I don't know where to put their UI components yet. Originally I wanted to make a new panel (like the custom tag panel) which can be hidden if the users don't need them.

**Comment by sway2020** [comment]
This is just a rough mockup of my plan now(it can be changed):

![Screenshot 1](https://user-images.githubusercontent.com/65274619/88575266-77fb0500-cff8-11ea-8be9-af571f5ce987.png)

The top panel will house new filters in #64, and probably some other potential features. The top two panels will only be shown when the users need them.

These new tool panel icons will be used to hide/show the top two panels. 
![Screenshot2](https://user-images.githubusercontent.com/65274619/88575306-8ba66b80-cff8-11ea-80cd-56ea987a5dae.png)

When the building filter panel is needed, it will replace the small tool icon panel
![PreviewImage4](https://user-images.githubusercontent.com/65274619/88575575-f5267a00-cff8-11ea-90f5-b6b5a055abf3.png)

I think #65 only applies to growable and RICO buildings, so I'll probably put a small button next to the 'All' button.

**Comment by sway2020** [comment]
This is how it looks like now.

![2133885971_preview_Screenshot 2](https://user-images.githubusercontent.com/65274619/88874054-f7dcc700-d1d2-11ea-83c5-8335c36dcfbe.png)
![2133885971_preview_Screenshot 9](https://user-images.githubusercontent.com/65274619/88874100-19d64980-d1d3-11ea-8dd7-38ba078b5906.png)
