### ISSUE TITLE
New Feature: Add Beautification categories for props (and decals?)

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#7]
Add the old categories as it was in the "More beautification" mod (https://steamcommunity.com/sharedfiles/filedetails/?id=505480567)

**Comment by sway2020** [comment]
I will check how it was implemented in More beautification and see the feasibility.

**Comment by sway2020** [comment]
The implementation is done and probably will be included in the next release after some more testing. Here's a [preview image](https://i.imgur.com/ftGrEu1.png)
