### ISSUE TITLE
Custom tag and additional filter tab are not available when Growable/Rico/ Growable.Rico prefilter is selected.

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#70]

**Comment by sway2020** [comment]
![88575306-8ba66b80-cff8-11ea-80cd-56ea987a5dae](https://user-images.githubusercontent.com/65274619/89049858-be0cdd00-d306-11ea-91d7-bd7f527e9ce0.png)

Do you mean this small panel? There isn't enough space for the icons to be displayed along with the building levels & size options. You can open those two panels by switching to other options(like 'All', 'Tree", "Network", etc.) first, and then switch to growable or rico.

**Comment by Sipke82** [comment]
Yes i mean those... Yes I figured the lack of space would be the issue.

Would be good if a solution could be found, as you probably need those buttons quite a lot in those categories

**Comment by sway2020** [comment]
Yup this is related to #68. I'll close this issue for now and if you have any idea or suggestion about UI changes you can leave it in #68.
