### ISSUE TITLE
bug: sometimes networks dont show all tools

### ISSUE THREAD

**Issue by Sipke82** [sway2020/FindIt2#77]
This bug was also already in the orignal find it.
For example with the surface roads: (https://steamcommunity.com/sharedfiles/filedetails/?id=2175361167&searchtext=surface+roads) 

Sometimes the road tools are gone:

![image](https://user-images.githubusercontent.com/30873812/89815197-a1fa0e80-db44-11ea-9cc8-e131ae8af11e.png)

**Comment by sway2020** [comment]
I noticed this issue too when I was working on #75. I know why it does this in the code and I'll try to fix it in the next beta update.

**Comment by sway2020** [comment]
@Sipke82 Just a quick update. Do you use Resize It? I'm no longer certain if this is caused by an inherited bug from Find It 1.

**Comment by Sipke82** [comment]
Yes I use resize it.

**Comment by sway2020** [comment]
I saw Biffa's new video today and he had the "upgrade" icon missing. Probably related to this issue but I don't know the cause yet.

**Comment by sway2020** [comment]
Should be fixed in the latest beta update(2.0.3-beta3) along with other related issues with the network options panel. I'll close this issue for now. @Sipke82 Feel free to let me know if it still happens and I'll reopen this issue.
