### ISSUE TITLE
Enhancement: Add thumbnail sharing with Ploppable RICO Revisited

### ISSUE THREAD

**Issue by algernon-A** [sway2020/FindIt2#9]
Save some memory, and prevent some crashes, by sharing thumbnails between the two mods when both are active.

Would require Ploppable RICO to add interface so Find It can access RICO's thumnail renders.  Interested?

**Comment by sway2020** [comment]
That's a wonderful idea! Let me know when the interface is done and I'll check what needs to be added to Find It.

**Comment by algernon-A** [comment]
I've also come up with another idea - defer thumbnail generation until the simulation has actually started.  Currently, RAM use peaks at the conclusion of loading (i.e. when `OnLevelLoaded `is running) - so RAM is most scarce at _exactly_ the point at which thumbnail generation currently takes place.

My plan is: load as normal, Ploppable RICO Revisited doing its normal thing during the actual load process.  When `OnLevelLoaded `is reached and `UIView.GetAView` is ready, RICO creates a new gameobject (attached to `GetAview` but with no visible UI components - just a single invisible 'dummy' `UIComponent`).  This then takes advantage of the game's horribly inefficient UI code to progressively generate the thumbnails which each call to Update, so the thumnails are only actively rendered once active memory management has kicked and RAM is more readily available.

In addition to the general 'background' updates, an interface method will also allow for forced rendering of a specific thumbnail as required (e.g. if the user opens a panel before rendering is fully complete).

Find It, in its turn, uses RICO's hooks to identify which buildings are RICO-managed and to retrieve the already-generated thumbnails.

If that works, then the same method could be reproduced within FindIt for the non-RICO thumnails and for when RICO isn't installed.

**Comment by sway2020** [comment]
@algernon-A I haven't really figured out how thumbnails are handled/rendered but from your description it seems like a feasible idea. Another idea I'm thinking about is an option for a "simple thumbnail mode" for players with smaller RAM. Afaik each asset has 5 thumbnail variations purely for visual effects? The idea is that in this mode every asset uses the same shared disabled thumbnail(probably just a black image or a stop sign). So this can reduce about 20% of thumbnail generation. For other states such as pressed or hovered, maybe it is possible to put a shared semi-transparent image on top of the default thumbnails? Each would save another 20%. From your experience with handling thumbnails in Rico revisited, do you think this is a feasible approach?

**Comment by algernon-A** [comment]
It's definitely possible to remove some of the visual variations, yes.  Hovered as an overlay could also work - I'll do some experiments with RICO and see how it goes.

**Comment by sway2020** [comment]
@algernon-A I'll also experiment the idea with the existing Find It code some time next week. I'll let you know if I have some good progress.

**Comment by originalfoo** [comment]
> or other states such as pressed or hovered, maybe it is possible to put a shared semi-transparent image on top of the default thumbnails?

The icon on a UI component can easily be colorised with the `.color` property IIRC, and I think the background panel can be colorised too. Could potentially save huge amounts of RAM if only a single icon is loaded per asset.

**Comment by sway2020** [comment]
I don't really understand/remember how thumbnails work(algernon did the work) but I think last time I checked Find It was only generating thumbnails for a few assets. The game already generates thumbnails for most assets and Find It is using those directly. I need to check it again

**Comment by algernon-A** [comment]
I think this issue can be closed now, as it was made obsolete by subsequent developments.

At the time, it made sense, where the mods were generating custom thumbnails for all assets and storing them indefinitely.  Now, both mods are only generating thumbnails on-demand, and rendered thumbnails are discarded once no longer needed, with zero ongoing memory requirements.
